### ISSUE TITLE
Milestone 2 feedback: 

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1048#2]
Must fix: 

- [ ] Rename files so that it is easier to identify what each file is. Currently, there are a lot of untitled files
- [ ] incorrect task 3: missing scripts folder and .py file
- [ ] savreen: missing EDA
